SELECT HIRE_DATE
FROM EMPLOYEES;

-- EXTRACT THE YEAR FROM THE HIRE_DATE
SELECT HIRE_DATE,FIRST_NAME, EXTRACT(YEAR FROM HIRE_DATE ) AS HIRED_YEAR
FROM EMPLOYEES
ORDER BY HIRE_DATE;


-- SELECT THE MONTHS FROM THE HIRE DATE

SELECT HIRE_DATE, FIRST_NAME, EXTRACT(MONTH FROM HIRE_DATE)  AS HIRED_MONTH
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC ;

-- FIND OUT ALL EMPLOYEE HIRED IN YEAR 2008

SELECT HIRE_DATE, FIRST_NAME, EXTRACT(YEAR FROM HIRE_DATE) AS HIRED_YEAR
FROM EMPLOYEES
WHERE  EXTRACT(YEAR FROM HIRE_DATE) BETWEEN  2001 AND 2003 ;

SELECT EXTRACT(YEAR FROM HIRE_DATE ) AS "HIRED YEAR", COUNT(*)
FROM EMPLOYEES
GROUP BY EXTRACT(YEAR FROM HIRE_DATE )
HAVING COUNT(*) > 15
ORDER BY EXTRACT(YEAR FROM HIRE_DATE) ASC ;


