
--ONE TABLE ON COMBINED WITH ANOTHER, THERE WILL BE DUPLICATES
SELECT * FROM FIRST_TABLE
    UNION ALL
SELECT * FROM SECOND_TABLE;

--RETURN COMBINED RESULTS BUT NO DUPLICATES
SELECT * FROM FIRST_TABLE
UNION
SELECT * FROM SECOND_TABLE;

SELECT * FROM FIRST_TABLE
MINUS
SELECT * FROM SECOND_TABLE;

SELECT * FROM SECOND_TABLE
MINUS
SELECT * FROM FIRST_TABLE;

SELECT * FROM SECOND_TABLE
INTERSECT
SELECT * FROM FIRST_TABLE;

