-- FIND OUT THE DEPARTMENT NAME AND THE MANAGER FIRST NAME

SELECT D.DEPARTMENT_NAME,D.MANAGER_ID, E.FIRST_NAME
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E
    ON D.MANAGER_ID = E.EMPLOYEE_ID
WHERE DEPARTMENT_NAME = 'Executive';

SELECT D.DEPARTMENT_NAME,D.MANAGER_ID, E.FIRST_NAME
FROM DEPARTMENTS D
         INNER JOIN EMPLOYEES E
                    ON D.MANAGER_ID = E.EMPLOYEE_ID
WHERE DEPARTMENT_NAME LIKE 'A%';

SELECT REGIONS.REGION_NAME, COUNT(COUNTRY_NAME) AS COUNTRY_COUNT
FROM COUNTRIES
INNER JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
GROUP BY REGIONS.REGION_NAME;