--FIND OUT MAX SALARY FROM EMPLOYEES

SELECT MAX(SALARY)
FROM EMPLOYEES;


--MAX SALARY
SELECT FIRST_NAME,SALARY
    FROM EMPLOYEES
WHERE SALARY =  (SELECT MAX(SALARY)
                FROM EMPLOYEES
                );

--MIN SALARY
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY =  (SELECT MIN(SALARY)
                 FROM EMPLOYEES);


SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES);


SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
                 FROM EMPLOYEES
                 WHERE SALARY != (SELECT MAX(SALARY) FROM EMPLOYEES));

SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Executive';

--
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID =(SELECT DEPARTMENT_ID
                      FROM DEPARTMENTS
                      WHERE DEPARTMENT_NAME = 'Executive'
);

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                      FROM DEPARTMENTS
                      WHERE DEPARTMENT_NAME IN ('Executive','Administration'));

--SUBQUERY CAN ALSO BE USED AS ENTIRE TABLE
-- FOR EXAMPLE SELECT * FROM (SUBQUERY GOES HERE)

SELECT FIRST_NAME, FIRST_NAME || LAST_NAME AS FULL_NAME
FROM EMPLOYEES;

SELECT *
FROM (SELECT FIRST_NAME, FIRST_NAME || LAST_NAME AS FULL_NAME
      FROM EMPLOYEES)
WHERE FULL_NAME = 'EllenAbel';

SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, EMPLOYEE_COUNT
FROM (SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
      FROM EMPLOYEES
      GROUP BY DEPARTMENT_ID);

SELECT FIRST_NAME, SALARY, DENSE_RANK() over (ORDER BY SALARY ASC )  AS SALARY_RANK
FROM EMPLOYEES;

SELECT *
FROM (SELECT FIRST_NAME, SALARY, DENSE_RANK() over (ORDER BY SALARY ASC )  AS SALARY_RANK
      FROM EMPLOYEES)
WHERE SALARY_RANK = 3;

CREATE TABLE EMP_SALARY_RANK  AS (
    SELECT FIRST_NAME, SALARY, DENSE_RANK() over (ORDER BY SALARY DESC )  AS SALARY_RANK
    FROM EMPLOYEES

);

SELECT * FROM EMP_SALARY_RANK
WHERE SALARY_RANK =4;








