SELECT * FROM EMPLOYEES;

-- CASE WHEN STATEMENT TO CONDITIONALLY DISPALY VALUES

--DISPLAY EMP FIRST NAME IF SALARY >
-- SALARY_GRADE SHOULD HAVE BELOW VALUES
--WHEN SALARY > 8000 -- " ABOVE AVERAGE "
-- ELSE " BELOW AVERAGE"

SELECT FIRST_NAME , SALARY,
       CASE WHEN SALARY > 20000 THEN 'A'
           WHEN SALARY BETWEEN 10000 AND 15000 THEN 'B'
           WHEN SALARY BETWEEN 5000 AND 1000 THEN 'C'
           ELSE 'D'
           END AS SALARY_GRADE2


FROM EMPLOYEES
ORDER BY SALARY;

-- TO DATE ACCEPT 2 PARAMETER
-- THE DATE STRING
-- THE FORMAT OF DATE PROVIDED IN PREVIOUS PARAMETER

SELECT FIRST_NAME, HIRE_DATE
    FROM EMPLOYEES
WHERE  HIRE_DATE < TO_DATE('2002-08-16','YYYY-MM-DD') ;


SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE  HIRE_DATE BETWEEN TO_DATE('2001-01-13','YYYY-MM-DD') AND TO_DATE('2006-01-03','YYYY-MM-DD');

