
CREATE TABLE FIRST_TABLE AS (
 SELECT FIRST_NAME, SALARY FROM EMPLOYEES
    WHERE SALARY BETWEEN 10500 AND 13000
    )ORDER BY 2;

CREATE TABLE SECOND_TABLE AS (
    SELECT FIRST_NAME, SALARY FROM EMPLOYEES
    WHERE SALARY BETWEEN 12000 AND 24000

)ORDER BY 2;
COMMIT;